version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  api:
    container_name: local.api.cadastro
    image: api
    volumes:
      - "./API:/var/www/html/:rw"
    environment:
      VIRTUAL_HOST: local.api.cadastro
      ENV_ALIAS: 'dev'
      #DATABASE
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: 'admin'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'neoway'
    build: .docker/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mongo
    command: ["/wait-for-it.sh", "mongo:27017", "--", ./assemble]
    tty: true
    #command: sleep 80000
  
  mongo:
    image: tutum/mongodb
    #restart: unless-stopped
    volumes:
     - .data/mongo:/data/db
    #command: mongod --smallfiles --oplogSize 128 --replSet rs0
    #labels:
    #  - "traefik.enable=false"
    ports:
      - "27017:27017"
    environment:
      VIRTUAL_HOST: mongo.local
      MONGODB_PASS: "neoway"
    expose:
       - "27017"

  spa:
    container_name: local.spa.cadastro
    environment:
      VIRTUAL_HOST: local.spa.cadastro
    image: node
    volumes:
      - "./SPA:/app:rw"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command:  /app/assemble
