FROM php:7.1-apache
EXPOSE 8080
RUN rm /etc/apt/preferences.d/no-debian-php
RUN apt-get update

#PHP
RUN apt-get update -y && apt-get install -y libpng-dev curl libcurl4-openssl-dev git zip unzip
RUN docker-php-ext-install pdo pdo_mysql gd curl zip
RUN docker-php-ext-install mysqli

#Apache
# sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
#RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
#RUN a2enmod rewrite